#!/usr/bin/env bash
# setup-wireguard-server.sh — one-time WireGuard server setup for reaching the
# budget web UI (and nothing else) over a private tunnel. Run once, as root,
# on the same VM that hosts budget-bot.service / budget-web.service.
#
# After this script finishes, use add-wireguard-peer.sh once per device
# (phone, laptop) to actually let a client connect.
set -euo pipefail

WG_DIR="/etc/wireguard"
WG_IFACE="${WG_IFACE:-wg0}"
WG_PORT="${WG_PORT:-51820}"
WG_SERVER_IP="${WG_SERVER_IP:-10.8.0.1}"
WG_SUBNET_CIDR="${WG_SUBNET_CIDR:-24}"

if [ "$(id -u)" -ne 0 ]; then
    echo "Run this as root (sudo $0)" >&2
    exit 1
fi

if [ -f "$WG_DIR/$WG_IFACE.conf" ]; then
    echo "$WG_DIR/$WG_IFACE.conf already exists — refusing to overwrite an existing setup." >&2
    echo "Delete it manually first if you really want to start over." >&2
    exit 1
fi

echo "Installing WireGuard..."
apt-get update -qq
apt-get install -y -qq wireguard qrencode

echo "Detecting default network interface for NAT..."
EGRESS_IFACE=$(ip route | awk '/^default/ {print $5; exit}')
if [ -z "$EGRESS_IFACE" ]; then
    echo "Could not auto-detect the default network interface." >&2
    echo "Set EGRESS_IFACE=<iface> and re-run." >&2
    exit 1
fi
echo "Using egress interface: $EGRESS_IFACE"

umask 077
mkdir -p "$WG_DIR/peers"
wg genkey | tee "$WG_DIR/server_private.key" | wg pubkey > "$WG_DIR/server_public.key"
SERVER_PRIVATE_KEY=$(cat "$WG_DIR/server_private.key")

cat > "$WG_DIR/$WG_IFACE.conf" <<EOF
[Interface]
Address = ${WG_SERVER_IP}/${WG_SUBNET_CIDR}
ListenPort = ${WG_PORT}
PrivateKey = ${SERVER_PRIVATE_KEY}
PostUp = iptables -A FORWARD -i ${WG_IFACE} -j ACCEPT; iptables -t nat -A POSTROUTING -o ${EGRESS_IFACE} -j MASQUERADE
PostDown = iptables -D FORWARD -i ${WG_IFACE} -j ACCEPT; iptables -t nat -D POSTROUTING -o ${EGRESS_IFACE} -j MASQUERADE

# Peers are appended below by add-wireguard-peer.sh — do not edit this file
# by hand once devices are added, or a manual edit could be lost on next run.
EOF
chmod 600 "$WG_DIR/$WG_IFACE.conf"

echo "Enabling IP forwarding..."
if ! grep -q '^net.ipv4.ip_forward=1' /etc/sysctl.conf 2>/dev/null; then
    echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf
fi
sysctl -p >/dev/null

if command -v ufw >/dev/null 2>&1; then
    echo "Opening UDP ${WG_PORT} in ufw..."
    ufw allow "${WG_PORT}/udp" >/dev/null
fi

systemctl enable "wg-quick@${WG_IFACE}" >/dev/null
systemctl start "wg-quick@${WG_IFACE}"

echo
echo "WireGuard server is up."
echo "  Interface:    ${WG_IFACE}"
echo "  Server IP:    ${WG_SERVER_IP}"
echo "  Listen port:  ${WG_PORT} (UDP)"
echo "  Public key:   $(cat "$WG_DIR/server_public.key")"
echo
echo "IMPORTANT — cloud firewall: if this VM is on a cloud provider (Oracle Cloud,"
echo "AWS, etc.), you must ALSO open UDP ${WG_PORT} in that provider's own"
echo "network security rules (Security List / Security Group / NSG) — ufw alone"
echo "is not enough on most cloud VMs."
echo
echo "Next step — add a device:"
echo "  sudo $(dirname "$0")/add-wireguard-peer.sh <device-name>"
echo
echo "Then set WEB_BIND_HOST=${WG_SERVER_IP} in your .env and restart budget-web.service."
